

from   ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

run apt update -y
run apt-get install  -y \
	git \
	build-essential \
	autoconf \
	cmake \
	libglu1-mesa-dev \
	libgtk-3-dev \
	libdbus-1-dev

ENV LANG=C.UTF-8
